### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by vlasvlasvlas** [mkenworthy/exorings#1]
hi when i execute this:

`python disk_sim.py -s 33000. -r 54220.65.try9.33kms.fits -d 54220.65.try9.33kms.fits -o 54220.65.try10.33kms.fits`

I got the following error:

```
Traceback (most recent call last):
  File "disk_sim.py", line 325, in <module>
    (rstart, rend) = exorings.ring_mask_no_photometry(kern, dstar, time, res[0], res[1], res[2], res[3])
  File "/home/USERNAME/smpch/devs/sandboxes/python/exorings/exorings/exorings.py", line 275, in ring_mask_no_photometry
    sgr[0] -= yc
TypeError: Cannot cast ufunc subtract output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

```

**Comment by mkenworthy** [comment]
Hello - I've updated the code for Python 3 - please pull down and see if it works!

**Comment by vlasvlasvlas** [comment]
thanks!
